# Adapted from https://github.com/catchorg/Catch2/blob/devel/.github/workflows/linux-simple-builds.yml
name: Linux build and test

on: [ push, pull_request ]

jobs:
  build:
    name: ${{matrix.cxx}}, C++${{matrix.std}}, ${{matrix.build_type}}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        cxx:
          - g++-10
          - g++-11
          - clang++-11
          - clang++-14
        build_type: [ Debug, Release ]
        std: [ 17 ]
        include:
          - cxx: g++-10
            other_pkgs: [ g++-10 ]
          - cxx: g++-11
            other_pkgs: [ g++-11 ]
          - cxx: clang++-11
            other_pkgs: [ clang-11 ]
          - cxx: clang++-14
            other_pkgs: [ clang-14 ]


    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Prepare environment
        # ubuntu-latest breaks without libunwind-dev,
        # see: https://github.com/actions/runner-images/issues/6399#issuecomment-1286050292
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libunwind-dev
          sudo apt-get install -y \
              ninja-build \
              libboost-thread-dev libboost-filesystem-dev libboost-log-dev libboost-stacktrace-dev \
              libssl-dev \
              libgstreamer1.0-dev \
              libevdev-dev \
              ${{ join(matrix.other_pkgs, ' ') }}

      - name: Configure build
        working-directory: ${{runner.workspace}}
        env:
          CXX: ${{matrix.cxx}}
          CXXFLAGS: ${{matrix.cxxflags}}
        # Note: $GITHUB_WORKSPACE is distinct from ${{runner.workspace}}.
        #       This is important
        run: |
          cmake -Bbuild -H$GITHUB_WORKSPACE \
                -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
                -DCMAKE_CXX_STANDARD=${{matrix.std}} \
                -DCMAKE_CXX_EXTENSIONS=OFF \
                -DCATCH_DEVELOPMENT_BUILD=ON \
                -G Ninja

      - name: Build tests + lib
        working-directory: ${{runner.workspace}}/build
        run: ninja -j 2 wolftests

      - name: Run tests
        working-directory: ${{runner.workspace}}/build/tests
        run: ./wolftests
