name: GitHub Pages Publish

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: asciidoctor-ghpages
      uses: manoelcampos/asciidoctor-ghpages-action@v2.2.4
      with:
        pdf_build: true
        source_dir: docs/ # default is .
        # asciidoctor_params: --attribute=nofooter
        # adoc_file_ext: .ascii # default is .adoc
        # slides_build: true
        # pre_build:
        # post_build:
