name: GitHub Pages Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: asciidoctor-ghpages
      uses: manoelcampos/asciidoctor-ghpages-action@v2.2.4
      with:
        pdf_build: true
        source_dir: docs/ # default is .
        asciidoctor_params: "-r asciidoctor-diagram" # add support for diagrams
        post_build: "git add -f *.svg"